### ISSUE TITLE
Provide option to get filled orders history

### ISSUE THREAD

**Issue by gitmalong** [openbook-dex/program#29]
This is something SerumDEX was never able to offer but is a mandatory requirement for everyone who does proper accounting for tax reports etc. With SerumDex filled order data was only temporary saved on the chain (that's my understanding) Can you please not forget about this and provide at least the technical feature to export a list of filled orders for a certain wallet?

**Comment by mschneider** [comment]
Actually @nicholasgodfreyclarke added some extra logging in 0.5.10 that will simplify building this kind of accounting system. It's underway and most likely will be a feature in mango v4 and other third party guis for serum.

**Comment by npomfret** [comment]
@gitmalong do you have any idea how to get the filled order data from the chain?
